# Generated by Django 4.2.2 on 2023-06-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
